### ISSUE TITLE
ssl encryption ? 

### ISSUE THREAD

**Issue by ingared8** [MySocialApp/kubernetes-helm-chart-cassandra#6]
Is it possible to use this chart with SSL encryption ? 

The truststore and keystore files could be mounted as a kuberntes secret.

```kubectl create secret cassandra-secret --from-file=cassandra.truststore.jks --from-file=cassandra.keystore.jks```

And similarly voume and volume mount can be attached to the statefulset.yaml

```
volume:
 - name: cassandra-certificates
    secret:
       name: cassandra-certificates
```
```
volumeMounts:
- name: cassandra-certificates
   mountPath: /opt/cassandra/certs
```
